=== agsha/open-media-flow-controller/mfc/nokeena/src/lib/cb/protocol/OCRP/dtd/OCRPupdate.dtd
<!-- OCRPupdate 1.0 DTD, Copyright (c) 2012 by Juniper Networks, Inc -->
<!ELEMENT OCRPupdate ((Entry*, DeleteEntry*)|(DeleteEntry*, Entry*))>
<!ELEMENT Entry (H, K, A*, L)>
<!ELEMENT H (#PCDATA)>
<!ELEMENT K (#PCDATA)>
<!ELEMENT A (#PCDATA)>
<!ELEMENT L (#PCDATA)>
<!ELEMENT DeleteEntry (H, K)>

=== agsha/open-media-flow-controller/mfc/nokeena/src/bin/cb/cgi/test1_ocrp_update.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE OCRPupdate SYSTEM "OCRPupdate.dtd">
<OCRPupdate>
 <DeleteEntry>
   <H>14:10</H>
   <K>/movies/category/xxx</K>
   </DeleteEntry>
 <Entry>
   <H>15:10</H>
   <K>/movies/category/action/TempleOfDoom.flv</K>
   <A>pin</A>
   <L>30.10.1.2:80:200,30.10.1.3:80:100</L>
 </Entry>
 <Entry>
   <H>16:10</H>
   <K>/movies/category/drama</K>
   <L>drama-int01:80:200,drama-int02:80:210</L>
 </Entry>
 <DeleteEntry>
   <H>17:10</H>
   <K>/movies/category/drama</K>
   </DeleteEntry>
</OCRPupdate>
