=== agsha/open-media-flow-controller/mfc/nokeena/src/lib/cb/protocol/OCRP/dtd/OCRP.dtd
<!-- OCRP 1.0 DTD, Copyright (c) 2012 by Juniper Networks, Inc -->
<!ELEMENT OCRP (Entry*)>
<!ELEMENT Entry (H, K, A*, L)>
<!ELEMENT H (#PCDATA)>
<!ELEMENT K (#PCDATA)>
<!ELEMENT A (#PCDATA)>
<!ELEMENT L (#PCDATA)>

=== agsha/open-media-flow-controller/mfc/nokeena/src/bin/cb/cgi/test1_ocrp_load.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE OCRP SYSTEM "OCRP.dtd">
<OCRP>
  <Entry>
    <H>0:10</H>
    <K>/movies/category/action/RaidersOfTheLostArk.flv</K>
    <A>pin</A>
    <A>pin</A>
    <A>pin</A>
    <A>pin</A>
    <L>10.10.1.2:80:255,10.10.1.3:80:1</L>
  </Entry>
  <Entry>
    <H>1:10</H>
    <K>/movies/category/action/RaidersOfTheLostArk.flv</K>
    <A>pin</A>
    <L>10.10.1.2:80:2,10.10.1.3:80:1</L>
  </Entry>
  <Entry>
    <H>2:10</H>
    <K>/movies/category/classics</K>
    <A>pin</A>
    <L>20.20.1.10:81:255,20.20.1.11:81:2</L>
  </Entry>
  <Entry>
    <H>3:10</H>
    <K>/movies/category/drama</K>
    <A>pin</A>
    <L>drama-int01:80:20,drama-int02:80:10</L>
  </Entry>
  <Entry>
    <H>4:10</H>
    <K>/movies/category/drama</K>
    <L>drama-int01:80:100,drama-int02:80:200</L>
  </Entry>
  <Entry>
    <H>5:10</H>
    <K>/movies/category/drama</K>
    <L>drama-int01:81:100,drama-int02:82:99,drama-int03:83:98,drama-int04:84:97,drama-int05:85:96,drama-int06:86:95,drama-int07:87:94,drama-int08:88:93</L>
  </Entry>
</OCRP>
